POST http://localhost:5223/meals
Content-Type: application/json

{
	"name": "Sticky Honey Lemon Chicken test2",
	"description": "30g protein. Winner winner, chicken dinner!",
	"macros": [{ "protein": 30 }, { "calories": 250 }, { "fat": 5 }],
	"duration": 60,
	"tags": ["Dinner", "High Protein", "chicken"],
	"ingredients": [
		"chicken",
		"lemon juice",
		"olive oil",
		"butter",
		"soy sauce",
		"honey",
		"parsley",
		"rice",
		"cilantro"
	],
	"seasoning": ["garlic powder", "cumin", "oregano"]
}