@id=101863b7-df99-4ece-baf7-696f9f6e6945

PUT http://localhost:5223/meals/{{id}}
Content-Type: application/json

{
    "name": "Rice bake 4",
	"description": "microwave it",
	"duration": "60",
	"tags": ["Dinner", "High Protein", "Chicken"],
	"ingredients": [
		"chicken",
		"lemon juice",
		"olive oil",
		"butter",
		"soy sauce",
		"honey",
		"parsley",
		"rice",
		"cilantro"
	],
	"seasoning": ["garlic powder", "cumin", "oregano"]
}