@id=f37a0ce0-1383-4698-b223-a5a65cbcfa6a

PUT http://localhost:5223/meals/{{id}}
Content-Type: application/json

{
    "name": "Sticky Honey Lemon TURKEY",
	"macros": [{ "calories": 320 }, { "protein": 31 }],
	"duration": "60 minutes",
	"tags": ["Dinner", "High Protein", "Chicken"],
	"ingredients": [
		"chicken",
		"lemon juice",
		"olive oil",
		"butter",
		"soy sauce",
		"honey",
		"parsley",
		"rice",
		"cilantro"
	],
	"seasoning": ["garlic powder", "cumin", "oregano"]
}